### ISSUE TITLE
Brush interaction not working on mobile

### ISSUE THREAD

**Issue by BrianRosamilia** [airbnb/visx#845]
(Enjoying the library, thanks for making it available)

I noticed the brush doesn't work with touch interactivity on mobile.  Example here: https://vx-demo.now.sh/brush

After digging into the code a bit, I noticed that mobile events don't seem to be wired up for the `Drag` component.  Shouldn't drag include touch and touchmove the same way as mouse and mousemove?

https://github.com/airbnb/visx/blob/master/packages/visx-drag/src/Drag.tsx#L121-L122

I could give it a shot if this is unintended and no one has time to look into it or is currently doing so.  Lmk

**Comment by williaster** [comment]
Hey @BrianRosamilia thanks for the bug report 🙏  I think this is simply an oversight with `@visx/drag`, it should support the touch events as you noted. 

Would happily review a PR if you want to take a shot!

**Comment by BrianRosamilia** [comment]
Can someone help me build the brush and its dependencies? 

Interestingly, the build for the brush points at the lib folder of `@visx/drag` and not at drag directly, which I'm noticing almost no other components do--so the instructions for building/debugging a single component don't actually work, as I see it :( 

https://github.com/airbnb/visx/blob/master/packages/visx-brush/src/BaseBrush.tsx#L4

**Comment by m9dfukc** [comment]
@BrianRosamilia did you make any progress with this? also came here because I noticed that the brush is broken on mobile :/

**Comment by iampueroo** [comment]
@williaster (quick FYI as I was perusing the open bugs again) - I believe this issue can be immediately closed, since #1155 was merged.

**Comment by shripadk** [comment]
Has this issue actually been fixed? I tried it on my mobile now (Android) and it isn't working.

**Comment by williaster** [comment]
I just played with it on mobile/android also, the brush moves but it's not a smooth experience/you can't really get it to do what you want. so looks like there's maybe some more validation/improvements that need to be made for that case.

**Comment by williaster** [comment]
Yep found a couple of refs that still have `onMouse...` in `@visx/brush`, should be a simple fix if anyone is interested! 

e.g.,
https://github.com/airbnb/visx/blob/master/packages/visx-brush/src/BrushCorner.tsx#L163

**Comment by williaster** [comment]
closed by #1286

**Comment by sakulstra** [comment]
@williaster are you sure this is fixed?
I tried on https://airbnb.io/visx/brush with my mobile device and it still seems to behave somewhat random.

**Comment by williaster** [comment]
yeppp, still not working I agree 🤦

**Comment by Stuhl** [comment]
Any progress?

**Comment by Avi-Patel** [comment]
Can this be fixed? 
Aur anyone knows about alternative i can use for mobile view?

**Comment by jconway325** [comment]
Do you have any updates on this?

**Comment by RyKilleen** [comment]
Would love to renew this issue.

It was an assumption of mine that this would work on mobile. Happy to put in some work if anyone knows the clear fix, or to spend some time identifying it.

**Comment by rubo** [comment]
Given that everything is mobile-first nowadays, it's a pity this issue hasn't been addressed yet. Could this be prioritized, please?

**Comment by hugolgst** [comment]
updates?

**Comment by eliza-guseva** [comment]
There were a couple more explicit `onMouse...` mentions in some Brush files. I believe the PR should fix the issue. At least with my forked version  my brushes in my graphs work on mobile

**Comment by hugolgst** [comment]
not sure what you did to make it work on mobile, with the latest version, for me, it still does not work

**Comment by kachkaev** [comment]
👋 @williaster WDYT of https://github.com/airbnb/visx/pull/1874? It’d be great to see something like that released to improve brush UX on touch devices. Not sure if there is an alternative until this issue is fixed, unless implementing Brush from scratch locally. That’d be quite laborious and error prone.

**Comment by neilgd** [comment]
I was wondering if this was ever fixed?

**Comment by hugolgst** [comment]
@neilgd i use this trick and it seems to work. hopefully it does for you

```js
useWindowMoveEvents={!isMobile}
```

**Comment by robbeman** [comment]
> [@neilgd](https://github.com/neilgd) i use this trick and it seems to work. hopefully it does for you
> 
> useWindowMoveEvents={!isMobile}

This works, partially, but the brush handles behave in strange ways on mobile.

For example:
1. You can drag the left handle out of bounds. (Also, when grabbing the left handle and dragging it to the right it will go out of bounds.)
2. Sometimes the handles disappear. You need to click around a bit on the right end and then they may reappear.
3. Sometimes the entire box is gone. (This may be intentional? Because then I can draw a new box by dragging the brush area.)

<img width="514" height="1035" alt="Image" src="https://github.com/user-attachments/assets/445a9e99-4d3a-43f8-91b8-e3271ba18f20" />

<img width="514" height="1035" alt="Image" src="https://github.com/user-attachments/assets/046b41d1-ac66-4756-bdf8-a07a3db39060" />

Codesandbox with mobile fix:
https://2kynxj.csb.app

**Comment by FinerDetails** [comment]
Any updates on [https://github.com/airbnb/visx/pull/1874](https://github.com/airbnb/visx/pull/1874)? 👀
